export const SAVE_AND_LOAD_CRAWLED_DATA_SUCCESS = 'SAVE_AND_LOAD_CRAWLED_DATA_SUCCESS';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
